curl 'https://nkb-backend-ccbp-prod-apis.ccbp.in/api/nkb_learning_resource/learning_resources/set/complete/' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer YKysSP61aiWrNqqTuKmXhxh8yD6MQ0' \
  -H 'content-type: application/json' \
  -H 'origin: https://learning.ccbp.in' \
  -H 'priority: u=1, i' \
  -H 'referer: https://learning.ccbp.in/' \
  -H 'sec-ch-ua: "Chromium";v="145", "Not:A-Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36' \
  -H 'x-app-version: 1127' \
  -H 'x-browser-session-id: 60b5d4c3-1598-4602-b497-a935c6611e3a' \
  --data-raw '{"data":"\"{\\\"learning_resource_set_id\\\":\\\"fc065063-d0c0-4b60-9ea7-c956bca78045\\\"}\"","clientKeyDetailsId":1}'